entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: cmc-net
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
